accounts/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('accounts.views',
    url(r'^profile/$', 'profile', name='profile'),
    url(r'^create/$', 'create_account', name='create'),
)

codemash/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, include, url


admin.autodiscover()


urlpatterns = patterns('',
    (r'^contact/', include('contact.urls', namespace='contact')),
    (r'^accounts/', include('django.contrib.auth.urls', namespace='auth')),
    (r'^accounts/', include('accounts.urls', namespace='account')),
    (r'^sponsors/', include('sponsors.urls', namespace='sponsors')),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', 'django.contrib.flatpages.views.flatpage', { 'url': '/' },
        name='home'),
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

codesmash/urls.py
from django.contrib import admin
from django.conf.urls import patterns, include, url

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^contact/', include('contact.urls', namespace='contact')),
    url(r'^accounts/', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^accounts/', include('accounts.urls', namespace='account')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'django.contrib.flatpages.views.flatpage',
        {'url': '/' }, name='home'),
)

contact/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('contact.views',
    url(r'^thanks/$', 'contact_thanks', name='thanks'),
    url(r'^$', 'contact_form', name='form'),
)

sponsors/urls.py
from django.conf.urls import patterns, include, url

from sponsors.views import UpdateSponsorView, SponsorshipListView


urlpatterns = patterns('sponsors.views',
    url('(?P<pk>[0-9]+)$', UpdateSponsorView.as_view(), name='update'),
    url(r'^$', SponsorshipListView.as_view(), name='home'),
)

talks/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('talks.views',
    url(r'^$', 'all_talks', name='index'),
)

accounts/models.py
from django.db import models

# Create your models here.

sponsors/models.py
from django.db import models
from django.contrib.auth.models import User


class SponsorshipLevelManager(models.Manager):

    def with_approved(self):
        query = super(SponsorshipLevelManager, self).get_query_set()
        return query.filter(sponsors__approved=True).exclude(sponsors=None)


class SponsorshipLevel(models.Model):

    objects = SponsorshipLevelManager()

    level_name = models.CharField(max_length=255)

    def __str__(self):
        return self.level_name

    def approved_sponsors(self):
        return self.sponsors.filter(approved=True)


class SponsorshipManager(models.Manager):

    def for_user(self, user):
        query = super(SponsorshipManager, self).get_query_set()
        return query.filter(sponsor=user)


class Sponsorship(models.Model):

    objects = SponsorshipManager()

    sponsor = models.ForeignKey(User, related_name="sponsorships")
    level = models.ForeignKey(SponsorshipLevel, related_name="sponsors")

    website = models.URLField(blank=True)
    website_copy = models.TextField(blank=True)
    logo = models.FileField(upload_to="sponsor_logos", null=True, blank=True)
    approved = models.BooleanField(default=False)

    def __str__(self):
        return "{self.sponsor} at {self.level}".format(self=self)

talks/models.py
from django.db import models


class Talk(models.Model):

    title = models.CharField(max_length=255)

    approved = models.NullBooleanField()
    recording_release = models.BooleanField(default=False)

    outline = models.TextField(blank=True)
    abstract = models.TextField(blank=True)
    notes = models.TextField(blank=True)

    def __str__(self):
        return self.title

    def __unicode__(self):
        return unicode(str(self))

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm


class RegistrationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        fields = ("username", "email")

contact/forms.py
from django import forms


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField()
    sender = forms.EmailField()

sponsors/forms.py
from django import forms

from sponsors.models import Sponsorship


class UserSponsorshipForm(forms.ModelForm):

    class Meta:
        model = Sponsorship
        fields = ("website", "website_copy", "logo")

talks/forms.py
from django import forms

from talks.models import Talk


class TalkForm(forms.ModelForm):

    class Meta:
        model = Talk
        exclude = ("approved", "location", "time_slot")

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login

from talks.models import Talk
from accounts.forms import UserCreationForm


def profile(request):
    return render(request, "accounts/profile.html", {
        'proposals': Talk.objects.all(),
    })


def create_account(request):
    form = UserCreationForm(request.POST or None)

    if request.method == "POST" and form.is_valid():
        form.save()

        user = authenticate(username=form.cleaned_data["username"],
                password=form.cleaned_data["password1"])
        login(request, user)

        return redirect("account:profile")

    return render(request, "accounts/create.html", {
        "form": form,
    })

codesmash/views.py
from django.shortcuts import render


def home(request):
    """The home page view
    """
    return render(request, "index.html")

contact/views.py
from django.core.mail import send_mail
from django.shortcuts import render, redirect

from contact.forms import ContactForm


def contact_form(request):
    form = ContactForm(request.POST or None)

    if request.method == "POST" and form.is_valid():
        send_mail(form.cleaned_data['subject'], form.cleaned_data['message'],
                form.cleaned_data['sender'], ['codesmash@example.com'])

        return redirect("contact:thanks")

    return render(request, 'contact/form.html', {
        'form': form,
    })


def contact_thanks(request):
    return render(request, "contact/thanks.html")

sponsors/views.py
from django.shortcuts import resolve_url
from django.views.generic import ListView
from django.views.generic.edit import UpdateView

from sponsors.forms import UserSponsorshipForm
from sponsors.models import Sponsorship, SponsorshipLevel


class SponsorshipListView(ListView):

    queryset = SponsorshipLevel.objects.with_approved()


class UpdateSponsorView(UpdateView):

    model = Sponsorship
    form_class = UserSponsorshipForm

    def get_success_url(self):
        return resolve_url("account:profile")

    def get_queryset(self):
        queryset = super(UpdateSponsorView, self).get_queryset()
        return queryset.filter(sponsor=self.request.user)

talks/views.py
# Create your views here.

templates/accounts/create.html
{% extends "base.html" %}

{% block content %}
<h1>Register an Account</h1>

<form method="post" action="{% url 'account:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Register" />
</form>
{% endblock %}

templates/accounts/profile.html
{% extends "base.html" %}
{% load icons %}

{% block content %}
<h1>Your Account</h1>
<p>Hello <b>{{ user.email }}</b></p>

<h1>Talk Submissions</h1>
<a href="{% url 'talks:create' %}">Submit Proposal</a>
<table>
    <tr>
        <th>Title</th>
        <th>Type</th>
        <th>Category</th>
        <th>Approved</th>
    </tr>
    {% for proposal in proposals %}
    <tr>
        <td><a href="{% url 'talks:update' proposal.id %}">{{ proposal.title }}</a></td>
        <td>{{ proposal.type }}</td>
        <td>{{ proposal.category }}</td>
        <td>{{ proposal.approved|boolean_icon }}</td>
    {% endfor %}
</table>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block title %}Hello Codemash{% endblock %}</title>
        <meta name="viewport" content="width=device-width">
    </head>
    <body>
        <ul>
            <li><a href="{% url 'home' %}">Home</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'account:profile' %}">Profile</a></li>
            <li><a href="{% url 'auth:logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'account:create' %}">Sign Up</a></li>
            <li><a href="{% url 'auth:login' %}">Login</a></li>
            {% endif %}
        </ul>
        {% block content %}
        {% endblock %}
    </body>
</html>

templates/contact/form.html
{% extends "base.html" %}

{% block title %}Hello Codemash{% endblock %}

{% block content %}
<h1>Contact Us</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Contact Us</button>
</form>
{% endblock %}

templates/contact/thanks.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Hello Codemash</title>
        <meta name="viewport" content="width=device-width">
    </head>
    <body>
        <h1>Thanks for contacting us!</h1>
    </body>
</html>

templates/index.html
{% extends "base.html" %}

{% block title %}Hello Codemash{% endblock %}

{% block content %}
<h1>Hello Codemash</h1>
<p>You've just created your first Django page. Pretty cool, eh?</p>
{% endblock %}

templates/sponsors/sponsorship_form.html
{% extends "base.html" %}

{% block title %}CodeMash Sponsors{% endblock %}

{% block content %}
<h1>Edit Sponsorship</h1>
<p>
    <label for="id_level">Level:</label>
    <input type="text" id="id_level" value="{{ object.level }}" disabled />
</p>
<p>
    <label for="id_approved">Approved:</label>
    <input type="checkbox" id="id_approved" {% if object.approved %}checked{% endif %} disabled />
</p>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save Changes" />
</form>
{% endblock %}

templates/sponsors/sponsorshiplevel_list.html
{% extends "base.html" %}

{% block title %}CodeMash Sponsors{% endblock %}

{% block content %}
<h1>Sponsors</h1>
<ul>
{% for level in object_list %}
<li><h2>{{ level.level_name }}</h2>
    <ul>
        {% for sponsor in level.approved_sponsors %}
        <li>
            {% if sponsor.logo %}
                <img src="{{ sponsor.logo.url }}" alt="{{ sponsor.sponsor }}" />
            {% endif %}
                <p>{{ sponsor.website_copy }}</p>
            {% if sponsor.website %}
                <p><a href="{{ sponsor.website }}">read more...</a></p>
            {% endif %}
            </li>
        {% endfor %}
    </ul>
</li>
{% endfor %}
</ul>
{% endblock %}

templates/talks/index.html
{% extends "base.html" %}

{% block content %}
<h1>Talks</h1>
<ul>
    {% for talk in object_list %}
    <li><h2>{{ talk.title }} ({{ talk.audience_skill_level }})</h2>
        <p><b>Presented In:</b></p>
        <p>{{ talk.location }} at {{ talk.time_slot }}</p>
        <p><b>Presented By:</b></p>
        <ul>
            {% for presenter in talk.proposers.all %}
            <li><a href="mailto:{{ presenter.email }}">{{ presenter.first_name }} {{ presenter.last_name }}</a></li>
            {% endfor %}
        </ul>
        <p>{{ talk.abstract }}</p>
        <p>{{ talk.outline }}</p>
    </li>
    {% endfor %}
</ul>
{% endblock %}

templates/talks/talk_form.html
{% extends "base.html" %}

{% block content %}
<h1>Submit Talk Proposal</h1>
<form action="" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>Talk Details</legend>
        {{ form.as_p }}
        <input type="submit" value="Save Changes" />
    </fieldset>
</form>
{% endblock %}

templates/talks/talk_list.html
{% extends "base.html" %}

{% block content %}
<h1>Talks</h1>
<ul>
    {% for talk in object_list %}
    <li><h2>{{ talk.title }} ({{ talk.audience_skill_level }})</h2>
        <p><b>Presented In:</b></p>
        <p>{{ talk.location }} at {{ talk.time_slot }}</p>
        <p><b>Presented By:</b></p>
        <ul>
            {% for presenter in talk.proposers.all %}
            <li><a href="mailto:{{ presenter.email }}">{{ presenter.first_name }} {{ presenter.last_name }}</a></li>
            {% endfor %}
        </ul>
        <p>{{ talk.abstract }}</p>
        <p>{{ talk.outline }}</p>
    </li>
    {% endfor %}
</ul>
{% endblock %}